export interface PropertyFractionalisation{
    id:string;
    iprojectId:string;
    propertyId:string;
	totalCostOfProperty:number;
	totalNoOfPropertyUnits:number;
	companyHoldingUnits:number;
	temporaryUnitsBlocked:number;
	gearedAmountOfProperty:number;
	totalAvailableUnitsForTrade:number;
	landPurchaseCost:number;
	legalCost:number;
	registrationCost:number;
	soldUnits:number;
	pricePerUnit:number;
	propertyValutaionDate:string;
	blockSize:number;
	createdDate:string;
	createdBy:string;
	modifiedDate:string;
	modifiedBy:string;
	gearingEffect:number;
	equity:number;
	spoValuation:number;
	acquisitionCost:number;
	developmentCost:number;
	platformCharges:number;
}